const zones={
  'Propylitic':{color:'#7ea867',confidence:84,depth:'18–900 m',volume:'0.92 Mm³',minerals:['Chlorite','Epidote','Calcite','Albite'],grade:'0.38',notes:'Broad chlorite–epidote alteration halo with patchy carbonate veining.'},
  'Argillic':{color:'#dccb74',confidence:78,depth:'30–700 m',volume:'0.47 Mm³',minerals:['Kaolinite','Illite','Smectite','Pyrite'],grade:'0.76',notes:'Clay-rich alteration concentrated above and lateral to the hot structural core.'},
  'Sericitic':{color:'#ead7bd',confidence:82,depth:'180–900 m',volume:'0.31 Mm³',minerals:['Sericite','Adularia','Quartz','Pyrite'],grade:'0.91',notes:'Quartz–adularia–sericite alteration forms the intermediate-temperature inner halo.'},
  'Advanced argillic':{color:'#ef9b68',confidence:91,depth:'60–900 m',volume:'0.34 Mm³',minerals:['Alunite','Pyrophyllite','Diaspore','Quartz'],grade:'1.82',notes:'High-temperature alunite–pyrophyllite alteration focused on the feeder structure.'},
  'Silicification':{color:'#6eb9c9',confidence:89,depth:'0–520 m',volume:'0.16 Mm³',minerals:['Vuggy silica','Quartz','Chalcedony','Pyrite'],grade:'2.14',notes:'Residual vuggy silica cap and steep quartz-rich feeder above the boiling level.'},
  'Steam-heated cap':{color:'#e7cf55',confidence:76,depth:'0–80 m',volume:'0.22 Mm³',minerals:['Kaolinite','Opal','Alunite','Native S'],grade:'0.03',notes:'Near-surface acid-sulphate alteration produced above the palaeo-water table.'},
  'Chalcedony blanket':{color:'#b7a2ca',confidence:81,depth:'70–150 m',volume:'0.19 Mm³',minerals:['Chalcedony','Quartz','Adularia'],grade:'0.42',notes:'Lateral silica blanket developed at the palaeo-water table and boiling horizon.'},
  'Ore zone':{color:'#e64d3f',confidence:94,depth:'100–850 m',volume:'0.08 Mm³',minerals:['Enargite','Pyrite','Covellite','Native Au'],grade:'3.46',notes:'Steep high-sulphidation Au–Cu feeder with stockwork mineralization in the upper-middle level.'}
};
let active='Advanced argillic', zoom=1, tagging=false, samples=24, allVisible=true, editingMarkId=null, pendingMark=null;
let markings=[];
let userLayers=[], drawingLayer=false, draftPoints=[], editingLayerId=null;
const layerList=document.querySelector('#layerList'), geoMap=document.querySelector('#geoMap'), toast=document.querySelector('#toast');

function renderLayers(filter=''){
  layerList.innerHTML='';
  Object.entries(zones).filter(([n])=>n.toLowerCase().includes(filter.toLowerCase())).forEach(([name,z])=>{
    const el=document.createElement('div'); el.className='layer-item'+(name===active?' selected':''); el.dataset.name=name;
    el.innerHTML=`<span class="swatch" style="background:${z.color}"></span><span><strong>${name}</strong><small>${z.custom?'DRAWN LAYER':z.minerals.length+' minerals'}</small></span><span class="eye">◉</span>`;
    el.onclick=()=>selectZone(name); el.querySelector('.eye').onclick=e=>{e.stopPropagation();toggleZone(name,el)}; layerList.append(el);
  });
}
function selectZone(name){active=name;document.querySelectorAll('.zone').forEach(z=>z.classList.toggle('selected',z.dataset.zone===name));const z=zones[name];
  document.querySelector('#detailPanel').style.visibility='visible';document.querySelector('#detailName').textContent=name;document.querySelector('#detailConfidence').textContent=z.confidence+'%';document.querySelector('#confidenceBar').style.width=z.confidence+'%';document.querySelector('#detailDepth').textContent=z.depth;document.querySelector('#detailVolume').textContent=z.volume;document.querySelector('#detailGrade').innerHTML=`${z.grade} <small>g/t</small>`;document.querySelector('#detailNotes').textContent=z.notes;document.querySelector('#detailAccent').style.background=z.color;document.querySelector('#mineralChips').innerHTML=z.minerals.map(m=>`<span>${m}</span>`).join('');renderLayers(document.querySelector('#layerSearch').value);renderUserLayers()}
function toggleZone(name,item){const paths=[...document.querySelectorAll('.zone')].filter(p=>p.dataset.zone===name);const hidden=!paths[0].classList.contains('hidden');paths.forEach(p=>p.classList.toggle('hidden',hidden));item.classList.toggle('off',hidden);item.querySelector('.eye').textContent=hidden?'○':'◉'}
function flash(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function addInitialSamples(){const g=document.querySelector('#samples');const pts=[[398,119],[414,137],[422,158],[406,183],[431,207],[416,228],[437,251],[421,276],[429,302],[418,330],[434,352],[423,377],[431,405],[420,433],[428,461],[383,143],[368,176],[459,152],[470,187],[386,247],[461,260],[397,317],[454,343],[407,394]];pts.forEach((p,i)=>{const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','sample');c.setAttribute('cx',p[0]);c.setAttribute('cy',p[1]);c.setAttribute('r',4);c.setAttribute('fill',i%4===0?'#f4b860':'#e5eee9');g.append(c)})}
function setZoom(v){zoom=Math.min(1.6,Math.max(.7,v));geoMap.style.transform=`scale(${zoom})`;document.querySelector('#zoomLevel').textContent=Math.round(zoom*100)+'%'}
function layerPath(points){return points.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ')+' Z'}
function saveUserLayers(){try{localStorage.setItem('terratag-user-layers',JSON.stringify(userLayers))}catch{flash('Layer saved for this session only')}}
function syncLayerData(layer){zones[layer.name]={color:layer.color,confidence:70,depth:'User defined',volume:'Not calculated',minerals:layer.minerals,grade:'—',notes:layer.note||'User-drawn interpretation boundary.',custom:true,id:layer.id}}
function loadUserLayers(){try{userLayers=JSON.parse(localStorage.getItem('terratag-user-layers'))||[]}catch{userLayers=[]}userLayers.forEach(syncLayerData);renderUserLayers()}
function renderUserLayers(){const group=document.querySelector('#customLayers');group.innerHTML='';userLayers.forEach(layer=>{const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',layerPath(layer.points));path.setAttribute('fill',layer.color);path.setAttribute('class','zone user-layer'+(active===layer.name?' selected':''));path.dataset.zone=layer.name;path.onclick=e=>{e.stopPropagation();selectZone(layer.name);renderUserLayers()};group.append(path);if(active===layer.name){layer.points.forEach((point,index)=>{const h=document.createElementNS('http://www.w3.org/2000/svg','circle');h.setAttribute('class','vertex-handle');h.setAttribute('cx',point.x);h.setAttribute('cy',point.y);h.setAttribute('r',6);h.dataset.index=index;h.onpointerdown=e=>{e.stopPropagation();h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(!h.hasPointerCapture(e.pointerId))return;const p=svgPoint(e);point.x=Math.max(0,Math.min(800,p.x));point.y=Math.max(0,Math.min(520,p.y));h.setAttribute('cx',point.x);h.setAttribute('cy',point.y);path.setAttribute('d',layerPath(layer.points))};h.onpointerup=e=>{if(h.hasPointerCapture(e.pointerId))h.releasePointerCapture(e.pointerId);saveUserLayers();flash(`${layer.name} boundary updated`)};group.append(h)})}})}
function startLayerDraw(){tagging=false;editingLayerId=null;draftPoints=[];drawingLayer=true;document.body.classList.add('drawing-layer');document.querySelector('#drawControls').hidden=false;document.querySelector('#mapHint').textContent='Click around the material boundary · Minimum 3 vertices';renderDraft();flash('Boundary drawing active')}
function renderDraft(){const g=document.querySelector('#drawPreview');g.innerHTML='';document.querySelector('#vertexCount').textContent=draftPoints.length;if(!draftPoints.length)return;const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',draftPoints.map(p=>`${p.x},${p.y}`).join(' '));g.append(line);draftPoints.forEach(p=>{const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r',5);g.append(c)})}
function cancelLayerDraw(){drawingLayer=false;draftPoints=[];document.body.classList.remove('drawing-layer');document.querySelector('#drawControls').hidden=true;document.querySelector('#drawPreview').innerHTML='';document.querySelector('#mapHint').textContent='Click a zone to inspect · Add a marking to annotate the section'}
function finishLayerDraw(){if(draftPoints.length<3){flash('Add at least 3 boundary vertices');return}drawingLayer=false;document.body.classList.remove('drawing-layer');document.querySelector('#drawControls').hidden=true;document.querySelector('#layerName').value=`New layer ${userLayers.length+1}`;document.querySelector('#layerColor').value='#42c6a2';document.querySelector('#layerMinerals').value='';document.querySelector('#layerNote').value='';document.querySelector('#deleteLayer').hidden=true;document.querySelector('#saveLayer').textContent='Save layer';document.querySelector('#layerDialog').showModal()}
function openLayerEditor(layer){editingLayerId=layer.id;document.querySelector('#layerName').value=layer.name;document.querySelector('#layerColor').value=layer.color;document.querySelector('#layerMinerals').value=layer.minerals.join(', ');document.querySelector('#layerNote').value=layer.note||'';document.querySelector('#deleteLayer').hidden=false;document.querySelector('#saveLayer').textContent='Save changes';document.querySelector('#layerDialog').showModal()}
function svgPoint(evt){const pt=geoMap.createSVGPoint();pt.x=evt.clientX;pt.y=evt.clientY;return pt.matrixTransform(geoMap.getScreenCTM().inverse())}
function renderMarkings(){
  const group=document.querySelector('#markings');group.innerHTML='';
  samples=24+markings.length;document.querySelector('#sampleCount').textContent=samples+' points';
  markings.forEach((mark,index)=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','marking'+(mark.id===editingMarkId?' selected':''));g.setAttribute('transform',`translate(${mark.x} ${mark.y})`);g.dataset.id=mark.id;g.innerHTML=`<circle class="mark-halo" r="13"/><circle class="mark-core" r="9" fill="${zones[mark.material].color}"/><text>${index+1}</text>`;
    let moved=false;
    g.addEventListener('pointerdown',e=>{e.stopPropagation();moved=false;g.setPointerCapture(e.pointerId);editingMarkId=mark.id;renderMarkIndex();g.classList.add('selected')});
    g.addEventListener('pointermove',e=>{if(!g.hasPointerCapture(e.pointerId))return;const p=svgPoint(e);mark.x=Math.max(12,Math.min(788,p.x));mark.y=Math.max(12,Math.min(508,p.y));g.setAttribute('transform',`translate(${mark.x} ${mark.y})`);moved=true});
    g.addEventListener('pointerup',e=>{if(g.hasPointerCapture(e.pointerId))g.releasePointerCapture(e.pointerId);if(moved){flash(`${mark.sampleId} position updated`);saveMarkings()}else openMarkEditor(mark.id)});
    group.append(g);
  });
  renderMarkIndex();
}
function renderMarkIndex(){const index=document.querySelector('#markIndex');document.querySelector('#markCount').textContent=markings.length;if(!markings.length){index.innerHTML='<div class="empty-index">No markings yet.</div>';return}index.innerHTML=markings.map((m,i)=>`<div class="mark-row ${m.id===editingMarkId?'active':''}" data-id="${m.id}"><span class="mark-number" style="background:${zones[m.material].color}">${i+1}</span><span><strong>${m.sampleId}</strong><small>${m.material}</small></span><span class="mark-edit">✎</span></div>`).join('');index.querySelectorAll('.mark-row').forEach(row=>row.onclick=()=>openMarkEditor(row.dataset.id))}
function openNewMark(){editingMarkId=null;pendingMark=null;document.querySelector('#dialogEyebrow').textContent='NEW OBSERVATION';document.querySelector('#dialogTitle').textContent='Add material marking';document.querySelector('#saveTag').textContent='Place marking';document.querySelector('#deleteMark').hidden=true;document.querySelector('#materialSelect').value=active;document.querySelector('#sampleId').value=`NR-${String(25+markings.length).padStart(3,'0')}`;document.querySelector('#sampleNote').value='';dialog.showModal()}
function openMarkEditor(id){const mark=markings.find(m=>m.id===id);if(!mark)return;editingMarkId=id;renderMarkings();document.querySelector('#dialogEyebrow').textContent='EDIT MARKING';document.querySelector('#dialogTitle').textContent=`Marking ${markings.indexOf(mark)+1}`;document.querySelector('#saveTag').textContent='Save changes';document.querySelector('#deleteMark').hidden=false;document.querySelector('#materialSelect').value=mark.material;document.querySelector('#sampleId').value=mark.sampleId;document.querySelector('#sampleNote').value=mark.note;dialog.showModal()}
function saveMarkings(){try{localStorage.setItem('terratag-markings',JSON.stringify(markings))}catch{flash('Marking saved for this session only')}}
function loadMarkings(){try{markings=JSON.parse(localStorage.getItem('terratag-markings'))||[]}catch{markings=[]}renderMarkings()}
loadUserLayers();renderLayers();selectZone(active);addInitialSamples();
document.querySelector('#layerSearch').oninput=e=>renderLayers(e.target.value);
document.querySelector('#allLayers').onclick=()=>{allVisible=!allVisible;document.querySelectorAll('.zone').forEach(z=>z.classList.toggle('hidden',!allVisible));renderLayers();flash(allVisible?'All layers visible':'All layers hidden')};
document.querySelectorAll('.zone').forEach(z=>z.onclick=e=>{e.stopPropagation();selectZone(z.dataset.zone)});
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.body.classList.toggle('confidence-mode',b.dataset.view==='confidence')});
document.querySelector('#zoomIn').onclick=()=>setZoom(zoom+.1);document.querySelector('#zoomOut').onclick=()=>setZoom(zoom-.1);document.querySelector('#resetView').onclick=()=>setZoom(1);
const dialog=document.querySelector('#tagDialog');document.querySelector('#materialSelect').innerHTML=Object.keys(zones).map(n=>`<option>${n}</option>`).join('');
document.querySelector('#tagBtn').onclick=openNewMark;document.querySelector('#newLayerBtn').onclick=startLayerDraw;document.querySelector('#exportBtn').onclick=()=>flash('Section NR-04 queued for export');document.querySelector('#editZone').onclick=()=>{const layer=userLayers.find(l=>l.name===active);layer?openLayerEditor(layer):flash('Reference geology is locked; draw a layer to create editable geometry')};document.querySelector('#closeDetails').onclick=()=>document.querySelector('#detailPanel').style.visibility='hidden';
document.querySelectorAll('.panel-tabs button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.panel-tabs button').forEach(b=>b.classList.toggle('active',b===btn));const index=btn.dataset.panel==='index';document.querySelector('#layersView').hidden=index;document.querySelector('#indexView').hidden=!index;document.querySelector('#panelHeading').textContent=index?'Marking index':'Material layers';document.querySelector('#allLayers').hidden=index;document.querySelector('#newLayerBtn').textContent=index?'＋ Add marking':'＋ Draw material layer';document.querySelector('#newLayerBtn').onclick=index?openNewMark:startLayerDraw});
document.querySelector('#saveTag').onclick=e=>{e.preventDefault();const data={material:document.querySelector('#materialSelect').value,sampleId:document.querySelector('#sampleId').value.trim()||'Untitled',note:document.querySelector('#sampleNote').value.trim()};if(editingMarkId){const mark=markings.find(m=>m.id===editingMarkId);Object.assign(mark,data);dialog.close();saveMarkings();renderMarkings();flash(`${mark.sampleId} updated`);return}pendingMark=data;active=data.material;selectZone(active);tagging=true;dialog.close();document.querySelector('#mapStage').style.cursor='crosshair';document.querySelector('#mapHint').textContent='Click the map to place the marking · Esc to cancel';flash('Placement mode active')};
document.querySelector('#deleteMark').onclick=()=>{if(!editingMarkId)return;const mark=markings.find(m=>m.id===editingMarkId);markings=markings.filter(m=>m.id!==editingMarkId);editingMarkId=null;dialog.close();saveMarkings();renderMarkings();flash(`${mark.sampleId} deleted`)};
document.querySelector('#mapStage').onclick=e=>{if(e.target.closest('.draw-controls'))return;if(drawingLayer){const p=svgPoint(e);draftPoints.push({x:p.x,y:p.y});renderDraft();return}if(!tagging||e.target.closest('.marking'))return;const p=svgPoint(e);const mark={id:`m-${Date.now()}`,x:p.x,y:p.y,...pendingMark};markings.push(mark);samples++;document.querySelector('#sampleCount').textContent=samples+' points';tagging=false;pendingMark=null;document.querySelector('#mapStage').style.cursor='';document.querySelector('#mapHint').textContent='Click a zone to inspect · Add a marking to annotate the section';saveMarkings();renderMarkings();flash(`${mark.sampleId} added to index`)};
document.querySelector('#undoVertex').onclick=e=>{e.stopPropagation();draftPoints.pop();renderDraft()};document.querySelector('#cancelLayer').onclick=e=>{e.stopPropagation();cancelLayerDraw()};document.querySelector('#finishLayer').onclick=e=>{e.stopPropagation();finishLayerDraw()};
document.querySelector('#saveLayer').onclick=()=>{const name=document.querySelector('#layerName').value.trim();if(!name){flash('Layer name is required');return}const minerals=document.querySelector('#layerMinerals').value.split(',').map(x=>x.trim()).filter(Boolean);if(editingLayerId){const layer=userLayers.find(l=>l.id===editingLayerId);delete zones[layer.name];Object.assign(layer,{name,color:document.querySelector('#layerColor').value,minerals,note:document.querySelector('#layerNote').value.trim()});syncLayerData(layer);active=layer.name}else{const unique=zones[name]?`${name} ${userLayers.length+1}`:name;const layer={id:`layer-${Date.now()}`,name:unique,color:document.querySelector('#layerColor').value,minerals,note:document.querySelector('#layerNote').value.trim(),points:draftPoints.map(p=>({...p}))};userLayers.push(layer);syncLayerData(layer);active=layer.name}draftPoints=[];editingLayerId=null;document.querySelector('#drawPreview').innerHTML='';document.querySelector('#layerDialog').close();saveUserLayers();renderUserLayers();selectZone(active);flash(`${active} saved`)};
document.querySelector('#deleteLayer').onclick=()=>{const layer=userLayers.find(l=>l.id===editingLayerId);if(!layer)return;delete zones[layer.name];userLayers=userLayers.filter(l=>l.id!==editingLayerId);active='Advanced argillic';editingLayerId=null;document.querySelector('#layerDialog').close();saveUserLayers();renderUserLayers();selectZone(active);flash(`${layer.name} deleted`)};
document.querySelector('#layerDialog').addEventListener('close',()=>{if(draftPoints.length){draftPoints=[];document.querySelector('#drawPreview').innerHTML='';document.querySelector('#mapHint').textContent='Click a zone to inspect · Add a marking to annotate the section'}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawingLayer){cancelLayerDraw();flash('Layer drawing cancelled');return}if(e.key==='Escape'&&tagging){tagging=false;pendingMark=null;document.querySelector('#mapStage').style.cursor='';document.querySelector('#mapHint').textContent='Click a zone to inspect · Add a marking to annotate the section';flash('Placement cancelled')}});
loadMarkings();
